#cloud-config

# Database Server Cloud-Init Configuration
# Clones from GitHub and sets up PostgreSQL database with monitoring

hostname: db-server
manage_etc_hosts: true

# Update system packages
package_update: true
package_upgrade: true

# Install essential packages
packages:
  - postgresql-14
  - postgresql-client-14
  - python3
  - python3-pip
  - git
  - curl
  - openssh-server
  - wget
  - htop
  - iotop
  - sysstat

# Setup SSH access
ssh_pwauth: false
disable_root: true

# Setup PostgreSQL
write_files:
  - path: /etc/postgresql/14/main/conf.d/custom.conf
    content: |
      # Custom PostgreSQL configuration
      listen_addresses = '*'
      max_connections = 100
      shared_buffers = 128MB
      effective_cache_size = 512MB
      maintenance_work_mem = 64MB
      checkpoint_completion_target = 0.9
      wal_buffers = 16MB
      default_statistics_target = 100
      random_page_cost = 1.1
      effective_io_concurrency = 200
      work_mem = 4MB
      min_wal_size = 1GB
      max_wal_size = 4GB

# System setup and application deployment
runcmd:
  # Create application directory
  - mkdir -p /home/ubuntu/app
  - chown ubuntu:ubuntu /home/ubuntu/app
  
  # Clone the GitHub repository
  - cd /home/ubuntu && git clone https://github.com/chmaikos/openstack-cloud.git app
  - chown -R ubuntu:ubuntu /home/ubuntu/app
  
  # Configure PostgreSQL
  - systemctl enable postgresql
  - systemctl start postgresql
  
  # Create database and user
  - sudo -u postgres psql -c "CREATE DATABASE cloudapp;"
  - sudo -u postgres psql -c "CREATE USER cloudapp WITH PASSWORD 'cloudapp123';"
  - sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE cloudapp TO cloudapp;"
  - sudo -u postgres psql -c "ALTER USER cloudapp CREATEDB;"
  
  # Install Python dependencies for database initialization
  - cd /home/ubuntu/app/application && pip3 install -r requirements.txt
  
  # Initialize database schema (run as ubuntu user)
  - su - ubuntu -c "cd /home/ubuntu/app/application && python3 init_db.py"
  
  # Configure PostgreSQL to accept connections from web server
  - echo "host    cloudapp    cloudapp    192.168.128.0/24    md5" >> /etc/postgresql/14/main/pg_hba.conf
  
  # Restart PostgreSQL to apply changes
  - systemctl restart postgresql
  
  # Download monitoring and health check scripts from GitHub
  - cd /home/ubuntu && wget -O monitor_db.sh https://raw.githubusercontent.com/chmaikos/openstack-cloud/main/scripts/monitor_db.sh
  - chmod +x /home/ubuntu/monitor_db.sh
  - chown ubuntu:ubuntu /home/ubuntu/monitor_db.sh
  
  - cd /home/ubuntu && wget -O health_check.sh https://raw.githubusercontent.com/chmaikos/openstack-cloud/main/scripts/health_check.sh
  - chmod +x /home/ubuntu/health_check.sh
  - chown ubuntu:ubuntu /home/ubuntu/health_check.sh
  
  # Setup log rotation for monitoring
  - |
    cat > /etc/logrotate.d/cloudapp-monitoring << 'EOF'
    /home/ubuntu/monitoring.log {
        daily
        missingok
        rotate 7
        compress
        notifempty
        create 644 ubuntu ubuntu
        postrotate
            echo "$(date): Log rotated" >> /home/ubuntu/monitoring.log
        endscript
    }
    EOF

# Final message
final_message: "Database server setup completed! PostgreSQL is running and database is initialized." 